version: "3.7"

services:
  zomboi:
    build: .
    volumes:
      - /path/to/maps:$MAPS_PATH
      - /path/to/logs:$LOGS_PATH
    environment:
      DISCORD_TOKEN: $DISCORD_TOKEN
      CHANNEL: $CHANNEL
      ADMIN_LOGS: $ADMIN_LOGS
      ADMIN_CHANNEL: $ADMIN_CHANNEL
      JOINS: $JOINS
      DISCONNECTS: $DISCONNECTS
      DEATHS: $DEATHS
      PERKS: $PERKS
      CREATECHAR: $CREATECHAR
      RCON_HOST: $RCON_HOST
      RCON_PASSWORD: $RCON_PASSWORD
      RCON_PORT: $RCON_PORT
      LOGS_PATH: $LOGS_PATH
      MAPS_PATH: $MAPS_PATH
    restart: unless-stopped
